### ISSUE TITLE
Create initial release

### ISSUE THREAD

**Issue by adamcharnock** [adamcharnock/lightbus#1]
# Goals

-  Ease of development & debugging
-  Excellent tooling & documentation
-  Targeting smaller teams
-  High speed & low latency (but not at the expense of other goals)

## MVP
- [x] Message transport layer
  - [x] ~~Message protocol (standard headers)~~ Handled by individual transports
- [x] Result transport layer
- [x] Api definition layer
  - [x] ``Api`` class
  - [x] ``Event`` class
  - [x] Metadata
  - [x] Registry
  - [x] API Autodiscovery
- [x] Event transport layer
- [x] Error responses
- [x] Ability to listen to multiple events with a single handler (already available in transports, just needs API)
- [x] Refactor marshalling code. We need a distinct place for the marshalling code to live, currently it is being pulled between the ``BusClient``, ``Message``, and ``XxxTransport`` classes.

## Required prior to use in production

- [x] Command line interface
- [x] Interactive REPL (`lightbus shell`)
- [x] Code cleanup (prior to schema / proper serialising & encoding)
- [x] Basic schema functionality
  - [x] Creation of jsonschema from method signatures
  - [x] `SchemaTransport`
  - [x] Exporting schema json
  - [x] Loading schema json
  - [x] Validation of outgoing RPC parameters
  - [x] Validation of incoming RPC parameters
  - [x] Validation of outgoing RPC responses
  - [x] Validation of incoming RPC responses
  - [x] Validation of outgoing event parameters
  - [x] Validation of incoming event parameters
- [x] Configuration system (yaml format? create jsonschema?)
  - [x] inConfig format
  - [x] Config loading
  - [x] Config validation
  - [x] Config loading on lightbus creation
  - [x] Make config available to `BusClient`
  - [x] Use bus-level config parameters
  - [x] Use api-level config parameters
  - ~~Api-level custom log levels~~ – Non-trivial implementation. Will leave for now.
  - [x] Plugin-level config
    - [x] Plugin-level config structure
    - [x] Create plugins using config options
    - [x] Respect `enabled` flag
  - [x] API-specific transports (non-critical)
  - [x] Work through in-code `config:` comments
- [x] Pass API name and event name to event handlers (& update examples)
- [x] Datetime type mapping
- [x] Short-form command line arguments
- [x] Deploy new docs (pending issue filed with GitHub)
- [x] Work through in-code TODOs
  - [x] Configuration options
  - [x] Move schema config to root level
- [x] Redis
  - [x] Update RPC transport to use PUBSUB?
  - [x] Update Event transport to use streams consumer groups
- [x] Add `stream_use` config option, which will allow for serving all events on the API from a single stream
- [x] Config loading from URL/~~Redis~~
- [x] ~~Pluggable configuration source~~ (Will do this if needed, we now support `http[s]://` urls anyway)
- [x] `@bus.on_start()` and `@bus.on_stop()`. *Consider refactoring plugins into this format too (the plugin system would have to operate around modules rather than classes, which may be a faff).*
- [x] `@bus.configure()` ~~to allow for per-service bus configuration. Is this a good idea?~~ (Leave for now, will revisit if there is a need)
- Look into (and implement?) structured logging ([see issue](https://github.com/hynek/structlog/issues/179)) - Now spun off into #10 
- [x] Implement synchronous context methods on `lightbus_set_database()`
- [x] Improve errors when performing RPC call with non-keyword arguments (check events too)
- [x] Improve schema validation errors
- [x] If event streaming – processing of events should stop if an error is encountered. *This won't be practical if running multiple workers.*
- [x] Cleanup python imports
- [x] Rename `BusNode` to something else. The 'node' term refers to the data structure it forms, but it can appear that a 'node' refers to the service.
- [x] Wait for redis the come up rather than dying on startup. Also lightbus should reconnect to redis. – *actually, is this a good idea? Should the process be running if it isn't operational. If we support reconnection (which we should) then we must accept the process will be running when it isn't operational. Perhaps only try for 60 seconds though.* – Implemented reconnections for rpc & event consumption. Decided that the pluggable nature of Lightbus' transports made it too hard to wait for redis to come up in a reliable way. Update: Lightbus now lazily connects to Redis, so that may go some way towards mitigating issues related to this point.
- [x] ~~**Transactional Transport**: The duplicates table needs to track uniqueness on **both** message ID *and* consumer name. Migration steps:~~ (Removed, see #4)
  - `ALTER TABLE lightbus_processed_events DROP CONSTRAINT lightbus_processed_events_pkey;`
  - `ALTER TABLE lightbus_processed_events ADD COLUMN listener_name VARCHAR(200);`
  - `UPDATE lightbus_processed_events SET listener_name = 'default';`
  - `ALTER TABLE lightbus_processed_events ADD PRIMARY KEY (message_id, listener_name);`
- [x] ~~**Django**: I suspect the transactional middleware creates a new postgres connection for every request.~~ (Removed, see #4)
- [x] Test RPCs/events with binary data
- [x] `consumer_group_prefix` -> `service_name`
- [x] `consume(consumer_group=...)` -> `consume(listener_name=...)`
- [x] `xxx.listen(fn, options["consumer_group"])` -> `xxx.listen(fn, listener_name="...")`
- [x] ~~Warn if duplicate consumer name used~~ (Less important now that `listener_name` is mandatory when setting up a new listener)
- [x] Explicit, non-global, API registration
  - [x] Docs
- [x] Config inheritance (in branch `feature/config-inheritance`. I'm not convinced this is a good idea)
  - ~~Docs~~ - Will leave this for now
- [x] Programatic scheduler
  - [x] Docs 
- [x] Non-global plugin registration
- [x] RFCs specifying protocol for all Redis transports
  - [x] Event
  - [x] RPC
  - [x] Result
  - [x] Schema
- [x] Fix CannotBlockHere exceptions / run user code in executors
- [x] Lazy-load schema
- [x] Migrate message IDs to UUIDs
- [x] Call to `xpending` should happen in a loop until there are no more messages
- [x] Standardise on command line argument position (before or after subcommand)
- [x] Cleanup old consumer groups and consumers

## Ideas for future work / notes:

- Ability to bypass bus overheads for local RPC calls ([suggestion](https://www.reddit.com/r/Python/comments/6qwg9p/lightbus_proposal_for_a_new_python_message_bus/)).
- Rename ``Meta`` to ``Options`` as this is more descriptive and doesn't clash with the 'metaclass' concept. Downside is that this diverges from Django.
- Store the last result result of each RPC call and event firing (for both success and failure). Need some kind of stats backend?
- Examine existing ways of defining API schemas: JSON schema (more generic), SWAGGER/OpenAPI (Rest-specific)
- Adding testing utilities: Assert RPC was called, assert event was fired etc
  - Support each API having stubs ([reference](http://www.draconianoverlord.com/2013/04/13/services-should-come-with-stubs.html))
    - There was an interesting article recently on different kinds of testing, in particular for services. Mocks v. stubs v. ?, but I cannot find it again.
  - It should be possible for your software to function (for development purposes) without anything else operating on the bus. (I.e. mocking/stubbing)
- Schema: https://pypi.python.org/pypi/schema ?
- Test against the [list of naughty words](https://github.com/minimaxir/big-list-of-naughty-strings) - it has some nice odd characters in there.
- Use [AlpaceJS](http://www.alpacajs.org/) to generate forms in admin UI based on JSON schema
- Create online configuration validator
- Use code comments to populate json schema description field. (doc strings, `#:` style. Parse parameter descriptions out of docstring?)
- Sanity check annotations for event listeners and RPCs. Issue a warning if annotated types are not JSON-compatible.
- [Management UI](https://github.com/adamcharnock/lightbus-admin) – consider refactoring away from React to something more lightweight. React is preventing me from wanting to pursue this further.

## Reading

- https://queue.acm.org/detail.cfm?id=1142044
- http://queue.acm.org/detail.cfm?id=1388786
- http://wiki.c2.com/?WhatsWrongWithEjb
- http://python-history.blogspot.co.uk/2009/01/pythons-design-philosophy.html
- https://martinfowler.com/articles/mocksArentStubs.html (for mocking apis, also [SO question](https://stackoverflow.com/questions/3459287/whats-the-difference-between-a-mock-stub))
- https://vimeo.com/111998645
- http://www.structlog.org/en/stable/ (Logging – copy API or use? Either way look into it)
- https://medium.com/codezillas/a-bitter-guide-to-open-source-a8e3b6a3c1c4

## Pre launch tasks

- [x] Create celery comparison &  migration guide
- [x] Create Django example + add docs for using with Django
- [x] `@uses_django_db()` - Either include in docs, or integrate it Lightbus core (Docs for now, see #6 for future improvements)
- [x] Create contributing guide
- [x] Create code of conduct
- [x] Create discourse room
- [x] Add python linting (done already?)
- [x] Initial benchmarks and caveat detailing that the project has yet to undergo any performance optimisations.
- [x] Finish docs
- [x] Document methods lacking docstrings
- [x] Release to Pypi

**Comment by adamcharnock** [comment]
Update: We now have Redis RPC & Result brokers working.

### Server

<img width="834" alt="screen shot 2017-10-08 at 17 45 37" src="https://user-images.githubusercontent.com/138215/31318867-bbc32836-ac50-11e7-92e2-09f41598bffb.png">


### Client

<img width="874" alt="screen shot 2017-10-08 at 17 45 52" src="https://user-images.githubusercontent.com/138215/31318861-b1837ef2-ac50-11e7-906f-d410b7579694.png">

**Comment by adamcharnock** [comment]
### Autodiscovery

I've decided to forgo autodiscovery for now. I think this could work well inside a predictable project structure – such as a Django project – but a general purpose solution would need to exhaustively import a lot of modules in order to discover ``bus.py`` modules.

I think this is probably doable, but for now it seems best to omit this particularly magical feature. I suspect more knowledge of Python's import system will be required to do this well.

Initial naive implementation was:

```python
# Initial naive (and abandoned) implementation of bus.py autodiscovery
def autodiscover(directory='.'):
    """Try to discover & import bus.py files"""
    lightbus_directory = Path(__file__).parent.resolve()
    # Find all bus.py files
    matches = [
        Path(match).resolve()
        for match
        in glob(str(Path(directory) / '**' / 'bus.py'), recursive=True)
    ]
    # Filter out any that are within the lightbus package
    matches = [m for m in matches if not str(m).startswith(str(lightbus_directory) + '/')]
    # Import each match
    for match in matches:
        # WARNING: This use of spec_from_file_location() is incorrect. The first parameter needs to 
        # be the entire module name, but here we just use 'bus'.
        spec = importlib.util.spec_from_file_location('bus', str(match))
        bus_module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(bus_module)
```

**Comment by adamcharnock** [comment]
After some thought, I think some basic autodiscovery will still be useful. Essentially using the first bus.py file yielded by a breadth-first search. Then determine the module name from sys.path, and perform the import.

However, only the top level bus.py file will be imported, anything else will have to be imported from there. Will attempt implementation

**Comment by adamcharnock** [comment]
Work has been continuing over the last few months. Items above are getting checked off pretty quickly now, so I'm hoping this proof of concept / MVP should be ready for the light of day in the next few months.

During this time we should also see the release of Redis 5.0, which will include streams ([ref](https://twitter.com/antirez/status/964562493665431552)).

**Comment by adamcharnock** [comment]
Latest thoughts on how to specify parameters for events. Unlike RPCs, event definitions are provided by class properties rather than methods. With RPCs we can extract the RPC signature from the method definition using Python's built-in `inspect` module.

With events we do not use method definitions as this would imply that there should also be an implementation. The implementation should live in the API's clients not the API itself. We therefore use class properties, but as a result we lose the ability to extract a parameter signature.

I've explored various ideas below regarding how we can specify parameters for events:

```python
# How can we specify parameters for events?

class TestApi(Api):
    # The current implementation
    user_registered1 = Event(parameters=['username', 'email', 'is_admin'])

    # Simple, no default values, no **kwargs
    user_registered2 = Event(parameters={'username': str, 'email': str, 'is_admin': bool})

    # Verbose, but has default values and **kwargs
    user_registered3 = Event(parameters=[
        inspect.Parameter('username', kind=inspect.Parameter.KEYWORD_ONLY, annotation=str),
        inspect.Parameter('email', kind=inspect.Parameter.KEYWORD_ONLY, annotation=str),
        inspect.Parameter('is_admin', kind=inspect.Parameter.KEYWORD_ONLY, annotation=str),
        inspect.Parameter('extra_fields', kind=inspect.Parameter.VAR_KEYWORD, annotation=str, default=False),
    ])

    # As above, but customised for more concise definitions
    user_registered4 = Event(parameters=[
        Parameter('username', str),
        Parameter('email', str),
        Parameter('is_admin', str),
        WildcardParameter('extra_fields', str, default=False),
    ])

    # Does not support **kwargs. Parameters can no longer be inline
    user_registered5 = Event(parameters=RegistrationEventParameters)
```

Where `RegistrationEventParameters` is:

```python
class RegistrationEventParameters(NamedTuple):
    username: str
    email: str
    is_admin: str = False
```

**Comment by adamcharnock** [comment]
What should the config system look like?

* Portable and transferable config
* Therefore no python files - something like `yaml`/`json` would be more suitable
* Can load config from various sources
  * File
  * URL
  * Redis key (Maybe.)
  * Are these just built in, or do we need a `ConfigTransport`?
* Ability to auto-reload process when config changes? Or perhaps that should be provided by a `config_changed` event on the state API?
* Ability to edit config in web UI

What different kinds of config are there:

- Global bus config
- Per API config
- Transport config

Future development:

* Per API config
  * e.g. different APIs can use different transports, timeouts etc

**Comment by adamcharnock** [comment]
Currently working on narrative documentation:

<img width="1177" alt="screen shot 2018-04-02 at 11 27 56" src="https://user-images.githubusercontent.com/138215/38193249-009532e0-3669-11e8-91e5-97e4a1cb2883.png">

**Comment by adamcharnock** [comment]
A quick review of the various registries we are using:

* Transport registry (internal to bus client)
* Plugin registry (global)
* API registry (global)
* Listener registry (internal to bus client, mostly for internal use)

Registries under consideration:

* Config loader registry

**Comment by adamcharnock** [comment]
Recording some notes on lightbus prometheus exporter metrics:

```
lightbus_listener_lag_events
lightbus_listener_processed_events
lightbus_listener_errors
lightbus_events_total
lightbus_called_rpcs
lightbus_processed_rpcs

labels:

    api_name
    event_name
    service_name
    transport_name

how:

    get_transport_metrics() method on transport
    get_listener_metrics() method on transport
```

**Comment by adamcharnock** [comment]
## Resolving CannotBlockHere errors

There has been an ongoing issue with the Lightbus API which looks something like this:

* Developer has a synchronous `on_start` handler
* Lightbus starts up, starts its event loop, and calls the synchronous `on_start` handler
* The `on_start` handler calls something like `bus.my.event.listen(...)`
* This is a thin wrapper which calls `block(bus.my.event.listen_async(...))`
* The `block()` utility tries to spin up an event loop in order to run the `listen_async` coroutine
* `block()` explodes with a `CannotBlockHere` exception because it is already running within an event loop, and you cannot nest event loops.

The solution to date has been that one must write async handlers (e.g `async def on_start()`) if one actually wishes to do anything which interacts with the bus (which is pretty much needed to do anything useful). This is not desirable as it forces async code on developers using Lightbus, rather than it being optional.

### The solution

The general solution to this is to run these hooks in an asyncio thread executor. Event loops are per-thread, so the hook its free to create its own loop as it now has its own thread.

There is a problem with this solution however: Lightbus has not been designed with treading in mind, and so is not threads-safe. Lightbus has been designed using asyncio, which puts lightbus in control of context switches (i.e. at any `await` statement). Threads on the other hand can context switch at any point.

Could Lightbus become thread safe? Most likely yes. However, I prefer to avoid this at this stage because 1) threading bugs are hard to track down, 2) I'm not particularly knowledgeable in this area, and 3) I would like Lightbus to stabilise more before embarking on this.

There is an alternative however. We are not using threads because we *need* threads, we are using threads to provide a clean environment for user code (i.e. an environment in which an event loop can be started). We therefore came to the following solution:

1. Only one asyncio task can be awake at once (across all threads). A global lock must be aquired in order to wakeup a task. This prevents arbitrary context switching within tasks.
2. The `BusClient` handles all bus interactions within the main thread when running as a worker. This ensures that the `BusClient` is only exposed to a single event loop.
3. What about when not running as a worker? Let's do a test with gunicorn.

**Comment by adamcharnock** [comment]
The above solution has now been implemented and merged. It appears to be working well.

**Comment by adamcharnock** [comment]
All development tasks are now complete. All that's left to go at the 'Pre launch tasks' which relate mostly to some additional documentation sections.

**Comment by adamcharnock** [comment]
Initial release is out! This epic issue can finally be closed, with all tasks complete 🎉
